### ISSUE TITLE
Typo in blog post GSA.getinformation -> GSA.getInformation

### ISSUE THREAD

**Issue by albertkuo** [OleAd/GeneralizedSpotifyAnalyser#1]
There is a small typo in a code chunk from the [blog post]( https://medium.com/analytics-vidhya/easily-analyse-audio-features-from-spotify-playlists-part-1-3b004cd406b3). `myPlaylist = GSA.getinformation(‘37i9dQZF1DX3hgbB9nrEB1’, verbose=True)`

**Comment by OleAd** [comment]
Thanks for spotting! Fixed now.
